### ISSUE TITLE
Results are remembered from previous skill check attempts

### ISSUE THREAD

**Issue by powerjeremy** [antontimmermans/MOMDATD#11]
In the office. When doing an observation test to pick up papers without harbour master knowing, on my second attempt of the test it remembered my result from the previous test. I had to manually reset the counter to 0 before performing the new test. (Minor i know. Not sure if this is supposed to happen)

**Comment by antontimmermans** [comment]
Hmm... may be default behaviour of Valkyrie. i will have to look into this one. I will chak also ask on Discord what other developers think of this.

**Comment by antontimmermans** [comment]
can solve this in the scenario.. (Fail test set check value to 0) will be updated in next version

**Comment by powerjeremy** [comment]
Yeah i haven't played any other scenarios. Maybe i should have so i could compare. It really isnt a big deal. Just something i noticed that was different from the official app.

**Comment by antontimmermans** [comment]
Solved in next version
