### ISSUE TITLE
Hunting horror moves towards hunting horror??

### ISSUE THREAD

**Issue by powerjeremy** [antontimmermans/MOMDATD#16]
I was fighting a hunting horror in the bell tower. He attacked me and i had to pass an agility test. The description says "then the monster moves 2 spaces toward the hunting horror.". *this is a known bug happening in other scenarios but im not sure if the author has to fix it in their scenario or not.

**Comment by antontimmermans** [comment]
Thank you for spotting this. It is a known bug in Valkyrie and is now planned to be addressed in version 2.4 see also https://github.com/NPBruce/valkyrie/issues/1010

**Comment by powerjeremy** [comment]
Oh ok... I was wondering if it was a problem with valkyrie itself. No problem.

**Comment by antontimmermans** [comment]
Solved in Valkyrie 2.4
