### ISSUE TITLE
Cryptex

### ISSUE THREAD

**Issue by chrismaliszewski** [antontimmermans/MOMDATD#19]
@chrismaliszewski @zcaalock  If I may ask you one more favor on the matter of the Polish language:

I have created a new puzzle in a style that was used in the film Da Vinci code: a Cryptex. It is currently set up for 26 letters A-Z, empty space and a dash '-'. (in total 28 positions). The graphics and button positioning should work on any device/screen aspect and resolution.

The attached scenario is quite simple: it will display the Cyptexpuzzle and with the up/down arrows, you can spell a 5 letter word with it. When you press "Guess" you will see a pass or fail text depending on if you guessed it right. _Hint: code word for this sample is the fruit (in English) that hit Newtons' head which resulted in his theory of gravity. ;-)_
[Cryptex.zip](https://github.com/antontimmermans/MOMDATD/files/3113749/Cryptex.zip)

I was wondering if this would be usable at all in the Polish language.  Would it require more than 28 values per digit to deal with the polish alphabet?

_Originally posted by @antontimmermans in https://github.com/antontimmermans/MOMDATD/issues/18#issuecomment-486380384_

**Comment by chrismaliszewski** [comment]
I checked how you the puzzle operates. A lot of "copy-paste" work you've done to make it operate :). Nice puzzle!

Base on that, I don't think implementing the Polish alphabet would be a problem even when it has more letters than English: https://upload.wikimedia.org/wikipedia/commons/c/c3/Polish-alphabet.png although it doesn't include Q, V & X letters. 

There is something else that **_is_** a major problem with the puzzle, no matter the language. In this instance, Polish and English are mostly nothing alike in terms of words. For example, the solution of the puzzle in Polish has 6 letters (you can use Google Translate so I'm not spoiling anything :)). 

Should the puzzle worked, it'd either require:
1. changing a riddle and its solution completely or,
2. changing just a solution, which may require a possibility to change the number of letters of the solution depending on the language

to create a riddle-solution match in less than 6 letters-riddle. 
In the latter option, it can sometimes be hard or even impossible to match the original meaning/word in other languages.

**Comment by chrismaliszewski** [comment]
There are two possibilities that I can think of to solve the problem in most of the cases: 
a. Would it be possible to create a mechanism that in real-time creates letters' positions depending on the length of the solution? Or...
b. Would it be possible to display only as many letters' positions as the solution has letters in EventStart/EventCryptexGuessPass?

In the second solution, you'd need to create a letter position as a separate graphic, it'd be a background, and somewhere in the code, a translator would need to write (add/remove) positions of the background depending on the number of letters the solution has. There could be a cheat-list that would say "if your password has X letters, place them in the positions: XXX to centre them."

What do you think?

**Comment by antontimmermans** [comment]
> I checked how you the puzzle operates. A lot of "copy-paste" work you've done to make it operate :). Nice puzzle!

True :) Thx.

> 
> Base on that, I don't think implementing the Polish alphabet would be a problem even when it has more letters than English: https://upload.wikimedia.org/wikipedia/commons/c/c3/Polish-alphabet.png although it doesn't include Q, V & X letters.
> 
> There is something else that **_is_** a major problem with the puzzle, no matter the language. In this instance, Polish and English are mostly nothing alike in terms of words. For example, the solution of the puzzle in Polish has 6 letters (you can use Google Translate so I'm not spoiling anything :)).
> 
> Should the puzzle worked, it'd either require:
> 
> 1. changing a riddle and its solution completely or,

Changing the riddle is can be handled in the translation file. But changing the solution would require language detection in the scenario script. I do not think there is a mechanism for that in Valkyrie at the moment.

> 2. changing just a solution, which may require a possibility to change the number of letters of the solution depending on the language
> 
> to create a riddle-solution match in less than 6 letters-riddle.
> In the latter option, it can sometimes be hard or even impossible to match the original meaning/word in other languages.

This would require different images to be loaded (can be done as described in the tutorial at page 63). But it would also require language based code to be executed to handle the 6 buttons instead of 5, which makes this the same problem as point 1.

> There are two possibilities that I can think of to solve the problem in most of the cases:
> a. Would it be possible to create a mechanism that in real-time creates letters' positions depending on the length of the solution? Or...
> b. Would it be possible to display only as many letters' positions as the solution has letters in EventStart/EventCryptexGuessPass?
> 
> In the second solution, you'd need to create a letter position as a separate graphic, it'd be a background, and somewhere in the code, a translator would need to write (add/remove) positions of the background depending on the number of letters the solution has. There could be a cheat-list that would say "if your password has X letters, place them in the positions: XXX to centre them."
> 
> What do you think?

Valkyrie supports language dependent images display and audio playback. But I do not know of a mechanism that allows for language dependent code execution. So in order to make this puzzle 'translatable' we would probably need language independent  solutions:
1. Number based: 10 digits+'empty space+dash': This will work but it will loose its charm because of the numbers instead of words, and it will start to look like the other (existing) code puzzle.
2. Symbols based: x-number of symbols: This will work too although I would carefully have to think about how to hand out the clues. Probably also some graphics of a piece of paper where the same symbols will appear on when you find them. But then the players would only need to copy what they find onto the puzzle which defies a bit the fun of the puzzle: trying a code based on hints to see if it works.
3. Use 5 letter words that are linked to the scenario;  names of scenario characters, or 'name of an elder one', or 'words of power'. These might be language independent and then you get the pull power of the puzzle: try words.  You can then also more easily add a extra layer of complexity. For example: you find the letters E T T P I and find out they don't work. Later you find a clue to shift all back 4 positions which makes it A P P L E which would be the right code. (in this example)

Currently my preference would be option 3, but maybe if I think a bit longer on it I could make it work to work with 'numbers only' (option 1) too.

**Comment by chrismaliszewski** [comment]
> Changing the riddle is can be handled in the translation file. But changing the solution would require language detection in the scenario script. I do not think there is a mechanism for that in Valkyrie at the moment.
> Valkyrie supports language dependent images display and audio playback. But I do not know of a mechanism that allows for language dependent code execution. 
> [...] But it would also require language based code to be executed to handle the 6 buttons instead of 5, which makes this the same problem as point 1.

I think determining if the possibility of executing code based on localization files is the key to the translatable solution of a riddle.

If so...
> This would require different images to be loaded (can be done as described in the tutorial at page 63). 

I'm not sure what you mean. A different set of CryptexClosed depending on the solution's length? You could do that but... If the above statement about being able to access localization files from events is true, you could either
1. leave a possibility to only create translatable riddles and 5-letter solutions or...
2. create the aforementioned set of CryptexClosed files and event which would fire another event depending on the length of a solution which would load the correct CryptexClosed file or...
2. do something nicer and create an event which would fire another one depending on the length of a solution which would build UI based on 3-4 images (depending upon one be flippable horizontally), these are:
![image](https://user-images.githubusercontent.com/7532602/56728846-e2931480-67a7-11e9-8578-9ad6ae86e671.png), ![image](https://user-images.githubusercontent.com/7532602/56728866-ecb51300-67a7-11e9-905e-335650df577d.png), ![image](https://user-images.githubusercontent.com/7532602/56728880-f3438a80-67a7-11e9-90f6-e63511067655.png)
(if the first image can't be flipped in Valkyrie, you'd need to create a 4th image flipped)

Regarding your ideas on the possible solutions. I either don't like 1. In terms of 3, again, I'm not following. If a solution is _**not**_ a proper noun but rather something else, it'll almost always be language-dependent. Additionally, let's say the solution of the riddle you created is a 'word of power', the word, for example, doesn't exist in Polish. What I'm trying to say is, solution 3 has its big limitations.

But number 2... It could be interesting! Depending on the image set, the solution could:
1. (language independent solution) be a number solution (see 1. of your suggestions),
2. (language independent solution) be a riddle of the kind: http://www.puzzles.com/puzzleplayground/NextSymbol/puzzle.gif, or...
3. (it isn't language independent but it's a nice idea :)) be a rebus, i.e. https://pl-static.z-dn.net/files/d47/0154dde0290cd7859be90553d85ed438.jpg. It'd be language-depended **_but_** it might be possible to create a riddle and a solution based on both changing clues' translation making it less language-independent than a word-based solution. Or...
4. (I think it'd be a language-independent solution although it might require more work on localization) be a story! Imagine the riddle "what happened to 3 little pigs?" with a solution of images of a pig, a wolf, a house, and wind and a pile of garbage (or something like that). Or, the story of a scenario could be the solution of the riddle! That's what a story-depended riddle would be called :). 

I think there could be more ideas of using images. It's obvious which one I consider the best possible solution :): number 2, as it can be a truly language-independent one. 

I still think it'd be good to make it certain on Discord if accessing localization files by events is somehow possible because it's the key element to create a word-based translatable solution of a riddle. 
Although, after consideration about the 2nd suggestion of yours, an image-based solution, I'd choose this one instead of word-based as it's more creative and might give more freedom + **_you wouldn't need to change anything in your code_** but images :).

**Comment by antontimmermans** [comment]
Something like: To open the path to truth you need to have the a keen eye, the right knowledge, a strong mind and twice the power of men:
{observation}+ {Lore}+ {Will}+ {Strength}+ {Strength} = Pass
This would not even require images but can be created with text UI items. I'll try make a version of that this weekend.

**Comment by antontimmermans** [comment]
Thanks for your input. Closing this ticket. The language 'independent'  Cryptex is available at repository antontimmemans\VSCL (see also referenced ticket see above)
