### ISSUE TITLE
Audio files VO - Docks

### ISSUE THREAD

**Issue by Steve-racer** [antontimmermans/MOMDATD#20]
Still learning GitHUB
[Docks.zip](https://github.com/antontimmermans/MOMDATD/files/3839219/Docks.zip)

**Comment by Steve-racer** [comment]
Script edits/changes

[Disturbance at the docsv2.docx](https://github.com/antontimmermans/MOMDATD/files/3839220/Disturbance.at.the.docsv2.docx)

**Comment by antontimmermans** [comment]
Updated scenario with the audio files in and published in v1.10

corrected name in credits v1.10a
