### ISSUE TITLE
Translation into Brazilian Portuguese

### ISSUE THREAD

**Issue by matBonet** [antontimmermans/MOMDATD#21]
I'm interested in translating this scenario into Brazilian Portuguese, how can I go about it?

**Comment by antontimmermans** [comment]
Thank you for choosing this scenario to translate.

For translations there are 3 methods described in this manual starting on page 178
https://docs.google.com/document/d/1Gi5gTwKkw84Px0Lvk-bJ3Aml_vF3ZoljjB6a8FjWGt8/edit?usp=sharing

With the Valkyrie app.
step 1 + With a plain (sourcecode) text editor; I recommend the Atom (free)
using all of the above including MS excel or the free google spreadsheets
Number three (starting on page 184) sounds most complicated but the guy who made the polish translation for this scenario was very happy with this method.

The end result will be that you create a localization.portuguese.txt file that you can attach to this ticket. I will then integrate this back into the scenario.

Let me know if you need help with any of these steps (for example extraction of the localization.english.txt or the set-up of the spreadsheet).

**Comment by antontimmermans** [comment]
The translation sheet is available on11:
https://docs.google.com/spreadsheets/d/1JCnp_r6y3MbOi8IqwygC2fvHPqlOMOe-u0AtZuYBEK8/edit#gid=0

**Comment by antontimmermans** [comment]
@Revokee I saw that you were also looking to translate the Disturbance at the docs scenario. With this, I link you to this ticket where you can discuss this.

Thanks in advance.

**Comment by Revokee** [comment]
[Localisation.Portuguese.txt](https://github.com/antontimmermans/MOMDATD/files/4657628/Localisation.Portuguese.txt)

Here is the localised file.

**Comment by antontimmermans** [comment]
The localization file is integrated into the scenario and ready for release.
Your translation is also added to https://docs.google.com/spreadsheets/d/1JCnp_r6y3MbOi8IqwygC2fvHPqlOMOe-u0AtZuYBEK8/edit#gid=0
Should I wait for your voice over files or is it ready for release like this?

**Comment by Revokee** [comment]
Adding the voices, I also reviewed some typos in the Spreadsheet above. Thanks!

[Portuguese.zip](https://github.com/antontimmermans/MOMDATD/files/4674594/Portuguese.zip)

**Comment by antontimmermans** [comment]
Super! it is released. many thanks friend!
