### ISSUE TITLE
"Disturbance at the docks" - Spanish translation.

### ISSUE THREAD

**Issue by vidimus** [antontimmermans/MOMDATD#22]
Hello.

I would like to start the Spanish translation of this scenario in the next few days. I've already done the first try, but I would prefer to do it in an official way, with the author's authorization and help.

**Comment by antontimmermans** [comment]
Hi vidimus,

Thank you for choosing this scenario to translate
For translations, there are 3 methods described in this manual starting on page 178
https://docs.google.com/document/d/1Gi5gTwKkw84Px0Lvk-bJ3Aml_vF3ZoljjB6a8FjWGt8/edit?usp=sharing
1. With the Valkyrie app.
2. step 1 + With a plain (sourcecode) text editor; I recommend the Atom (free)
3. using all of the above including MS excel or the free google spreadsheets

Number three (starting on page 184) sounds most complicated but the guy who made the polish translation for this scenario was very happy with this method.

The end result will be that you create a localization.spanish.txt file that you can attach to this ticket. I will then integrate this back into the scenario.

I can also prepare a translation file that can be edited with the free googlesheets app as I did with https://github.com/antontimmermans/MOMCDM/issues/10
In that case, I would need your email address to grant you edit access. ( and I would need a little time to create the translation spreadsheet :) )
For more privacy, you can send your email in a Private Message on discord (brotim).

**Comment by antontimmermans** [comment]
I have prepared a google spreadsheet document with the prepared column for the Spanish translation. https://docs.google.com/spreadsheets/d/1JCnp_r6y3MbOi8IqwygC2fvHPqlOMOe-u0AtZuYBEK8/edit#gid=0
I need your email address to grant you access to edit the file. For more privacy, you can send that in a Private Message on discord (brotim).

It contains (draft) translations from google translate. You can edit the text in this spreadsheet to make a proper translation. All the cells containing text that start with google: need verification or translation.
You can signal me when you confirmed or translated all Spanish text. I will then make the localization.txt file for it.

Tips and tricks for translation can be found in the manual: https://docs.google.com/document/d/1Gi5gTwKkw84Px0Lvk-bJ3Aml_vF3ZoljjB6a8FjWGt8/edit

**Comment by gustavoberman** [comment]
Hi there!
I can help with spanish translation

**Comment by antontimmermans** [comment]
you should be able to edit it using this link: https://docs.google.com/spreadsheets/d/1JCnp_r6y3MbOi8IqwygC2fvHPqlOMOe-u0AtZuYBEK8/edit?usp=sharing

**Comment by gustavoberman** [comment]
> 
> 
> you should be able to edit it using this link: https://docs.google.com/spreadsheets/d/1JCnp_r6y3MbOi8IqwygC2fvHPqlOMOe-u0AtZuYBEK8/edit?usp=sharing

This link is "view only", I´d sent you an edit request.

**Comment by antontimmermans** [comment]
I didn't see a pending request on this sheet for editing, but I opened the sheet for editing for everyone who has the link: https://docs.google.com/spreadsheets/d/1JCnp_r6y3MbOi8IqwygC2fvHPqlOMOe-u0AtZuYBEK8/edit?usp=sharing

Can you try again please?

**Comment by gustavoberman** [comment]
Perfect.
Already started with Spanish translation.

**Comment by antontimmermans** [comment]
How is the translation going guys? need any help?

**Comment by vidimus** [comment]
> How is the translation going guys? need any help?

In my case, I'm with the first scenario of Scrubbless's campaign "The Strain". 

Sometimes I translate a few lines of "Disturbance". I don't know if @gustavoberman is working with the file or not but probably I could help with "Disturbance at the docks" when I finished my current task.

**Comment by vidimus** [comment]
10% to finish it.

**Comment by vidimus** [comment]
The translation is finished. Now I will do some testing.
I've also checked the "Chapel down manor" text and corrected some typos.
I will comment here when both scenarios were ready.

**Comment by vidimus** [comment]
Hello, @antontimmermans 
"Disturbance at the docks" translation is ready to be used. "Chapel Down Manor" one has been reviewed and it's ready for update. 
As usual, once published I will find more bugs...

**Comment by vidimus** [comment]
Thanks for uploading so fast the translation, @antontimmermans 

I expect to receive some feedback about the translation. So probably I would update the file in a few weeks. I will notice you.

**Comment by antontimmermans** [comment]
great, and thanks again for your hard work.

I will close this ticket for now. for an update, just let me know via the google doc comment or re-open this ticket  .. or write a new one ;-)

Muchas gracias!

**Comment by vidimus** [comment]
Absolutely, Anton.
Waiting for your new scenario!

¡De nada! Graag gedaan! (I googled it, "sorry, ik spreek geen Neerderlans).
