### ISSUE TITLE
"Disturbance at the docks" - French translation.

### ISSUE THREAD

**Issue by Mickski** [antontimmermans/MOMDATD#23]
Hello Anton,

  I would like to translate your scenario into french. 

  If you agree, could you prepare the Gsheet document with a new column for french and provide me the suitable link so that I could start the job, like you've done for vidimus and his spanish translation?

  Thank you.

Regards.

**Comment by antontimmermans** [comment]
column G contains the Google French https://docs.google.com/spreadsheets/d/1JCnp_r6y3MbOi8IqwygC2fvHPqlOMOe-u0AtZuYBEK8/edit#gid=0

**Comment by Mickski** [comment]
Great Anton! 

Now all is set to proceed.

Thanx.

**Comment by mponsot** [comment]
Hi,

I haven't seen this post and did a French translation on my side. Here's the link to the file :

[Localization.French.txt](https://github.com/antontimmermans/MOMDATD/files/4673208/Localization.French.txt)

**Comment by antontimmermans** [comment]
Thank you very much for your translation. I have added the translation to the google doc to keep it in sync with the other languages. https://docs.google.com/spreadsheets/d/1JCnp_r6y3MbOi8IqwygC2fvHPqlOMOe-u0AtZuYBEK8/edit#gid=0
If you change/improve texts in the spreadsheet, you can just let me know on discord or on this ticket. I will then make a new version of the localization file out to that spreadsheet.

Your Translation will be released in version 1.14 (today) and I added **mpnsot** in the credits as a french translator.

I will announce the translation on discord and on BGG.

**Comment by mponsot** [comment]
Hi again !

I just tried to run the scenario in Valkyrie and it stays stuck at the begining. 
After the "start items" screen, i can see the 'each investigator starts with 2 clues' and then switch to a green background image and never moves on.

**Comment by antontimmermans** [comment]
I am fairly sure the translation is not the problem, I am running the scenario with Valkyrie 2.4.07. On discord are messages about the performance of the new windows build. That may be the problem. I will keep an eye on it though.
