### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by cinek190** [antontimmermans/MOMDATD#24]
Hello. The Polish translation has the letter 'n' missing at the beginning of every word that starts with it. If the 'n' is the second or any subsequent letter of a word, it's fine.

**Comment by zcaalock** [comment]
musiał nastąpić jakiś błąd przy konwertowaniu tekstu i ucięło znak specjalny następnej linii "/n". Dzięki za zwrócenie uwagi

**Comment by cinek190** [comment]
Bardzo prosze. A raczej dziekuje za przetlumaczenie tego scenariusza, jak i licznych innych. Swietna robota.


    On Sunday, 4 October 2020, 13:38:50 CEST, zcaalock <notifications@github.com> wrote:  
 
 


musiał nastąpić jakiś błąd przy konwertowaniu tekstu i ucięło znak specjalny następnej linii "/n". Dzięki za zwrócenie uwagi

**Comment by antontimmermans** [comment]
Solved in version 2.0d
