### ISSUE TITLE
Italian translations

### ISSUE THREAD

**Issue by GabroDonuts** [antontimmermans/MOMDATD#26]
Hi, I would translate your scenarios in italian. Is it ok for you? thank you :)

**Comment by antontimmermans** [comment]
HI, You probably found your way to https://docs.google.com/spreadsheets/d/1JCnp_r6y3MbOi8IqwygC2fvHPqlOMOe-u0AtZuYBEK8/edit#gid=0 already. Please let me know if you need support or when you are done

**Comment by antontimmermans** [comment]
i suppose there is no progress on this issue, I will close it.
