### ISSUE TITLE
Discrepancy on the skill check for the shop door

### ISSUE THREAD

**Issue by andrikos** [antontimmermans/MOMDATD#27]
<img width="1920" alt="shop1" src="https://user-images.githubusercontent.com/3123918/114113858-ef9b6680-98df-11eb-9d57-7659f3f19b62.png">
<img width="1920" alt="shop2" src="https://user-images.githubusercontent.com/3123918/114113864-f1fdc080-98df-11eb-8410-a9d28e264e06.png">

Hi,

I'm attaching screenshots for the locked shop door check.
The initial screen mentions Agility skill (shop1.png), but the real test shows Observation skill (shop2.png)

Thanks for the great story,
Nikos

**Comment by antontimmermans** [comment]
Good find after so many plays. 
I will make a fix a.s.a.p.

**Comment by antontimmermans** [comment]
Solved in version 2.0i
