### ISSUE TITLE
Czech translate

### ISSUE THREAD

**Issue by LabBrab** [antontimmermans/MOMDATD#30]
Hi Anton,

I translated your next scenario - Disturbance at The Docks into Czech language. I am attaching the file. I'll be happy if you add him to Valkyrie soon.

Best regards

LabBrab

**Comment by LabBrab** [comment]
[Localization.Czech.txt](https://github.com/user-attachments/files/17088656/Localization.Czech.txt)

Thanks!

**Comment by antontimmermans** [comment]
@LabBrab thank you for your translation and your effort to make Valkyrie scenarios more accessible to the Czech-speaking gaming community. Your translation is added to the scenario and published.
